### ISSUE TITLE
bug: it refreshes every 15 server minutes, when it said 30 minutes?

### ISSUE THREAD

**Issue by drelicious** [Drelicious/drelAuthPlugin#3]
I found out that it refreshes every ~15 minutes instead of 30 minutes?

![image](https://user-images.githubusercontent.com/19788638/194755991-78a5d279-532c-4620-9e57-086b25e44252.png)

**Comment by Drelicious** [comment]
if anyone want to send a pull request regarding of this issue, you're welcome.. it's just a matter of changing the title from 30 minutes to 15 minutes or you can multiply that 18000L * 2 = 36000L

**Comment by drelicious** [comment]
if anyone want to send a pull request regarding of this issue, you're welcome.. it's just a matter of changing the title from 30 minutes to 15 minutes or you can multiply that 18000L * 2 = 36000L

**Comment by smiti-maheshwari** [comment]
Hey @Drelicious, 

Can I work on this?

**Comment by drelicious** [comment]
> Hey @Drelicious,
> 
> Can I work on this?

yap.
